Repository react-hook-form/react-hook-form, pull requests merged in 2020-05, with the labels that each got.

#1531 🐞 fix react-hook-form#1520 return proper proxy object
  src/useForm.test.tsx
  src/useForm.ts
Labels: waiting-up-vote

#1569 improve FieldName type
  src/contextTypes.ts
  src/logic/appendErrors.ts
  src/logic/assignWatchFields.ts
  src/logic/getFieldArrayValueByName.ts
  src/logic/getFieldsValues.ts
  src/logic/shouldRenderBasedOnError.ts
  src/types.ts
  src/useForm.ts
  src/utils/getPath.ts
Labels: TS

#1508 feature: useWatch custom hook
  app/src/app.tsx
  app/src/useWatch.tsx
  cypress/integration/useWatch.ts
  src/index.ts
  src/logic/getFieldsValues.ts
  src/types.ts
  src/useForm.test.tsx
  src/useForm.ts
  src/useWatch.test.ts
  src/useWatch.ts
Labels: status: working in progress

#1578 rename types
  src/contextTypes.ts
  src/types.ts
  src/useFieldArray.ts
  src/useForm.ts
  src/useFormContext.tsx
  src/useWatch.ts
Labels: TS, status: working in progress

#1634 Feature/dirty fields to object
  .circleci/config.yml
  .github/workflows/automation.yml
  app/src/conditionalField.tsx
  app/src/formState.tsx
  app/src/formStateWithSchema.tsx
  app/src/setValueCustomRegister.tsx
  app/src/useFieldArray.tsx
  cypress/integration/conditionalField.ts
  cypress/integration/formState.ts
  cypress/integration/formStateWithSchema.ts
  cypress/integration/setValueCustomRegister.ts
  cypress/integration/useFieldArray.ts
  package.json
  src/logic/findRemovedFieldAndRemoveListener.ts
  src/logic/getSortedArrayFieldIndexes.ts
  src/types.ts
  src/useFieldArray.test.ts
  src/useFieldArray.ts
  src/useForm.test.tsx
  src/useForm.ts
  src/utils/filterBooleanArray.ts
  src/utils/get.ts
  src/utils/remove.test.ts
  src/utils/remove.ts
  src/utils/unique.ts
  src/utils/unset.test.ts
  src/utils/unset.ts
Labels: status: working in progress

#1646 improve useWatch type
  src/types.ts
  src/useWatch.ts
Labels: TS

#1663 fix register type to accept null argument
  src/types/contextTypes.ts
  src/useForm.ts
Labels: TS

#1697 add TypeScript example
  examples/README.md
  examples/nativeMultipleInput.tsx
  examples/types/Control.tsx
  examples/types/NestedValue.tsx
  examples/types/OnSubmit.tsx
  examples/types/Resolver.tsx
  examples/types/UseFormMethods.tsx
Labels: TS
