Repository react-hook-form/react-hook-form, pull requests merged in 2020-03, with the labels that each got.

#1178 fix FieldErrors to allow any type
  src/types.ts
Labels: status: working in progress

#1139 Feature/reset omit state update
  src/types.ts
  src/useForm.ts
Labels: waiting-up-vote

#1277 :bug: Fixing a bug related with testcafe.
  src/utils/swap.ts
Labels: stats: pending for verify

#1275 allow React.ReactElement in register option's message
  src/__snapshots__/errorMessage.test.tsx.snap
  src/contextTypes.ts
  src/errorMessage.test.tsx
  src/logic/__snapshots__/validateField.test.tsx.snap
  src/logic/getValidateError.ts
  src/logic/getValueAndMessage.ts
  src/logic/validateField.test.tsx
  src/logic/validateField.ts
  src/types.ts
  src/useForm.test.tsx
  src/useForm.ts
  src/utils/isMessage.test.ts
  src/utils/isMessage.ts
Labels: enhancement

#1293 fix #1290 with useFieldArray watch issue
  src/logic/assignWatchFields.test.ts
  src/logic/assignWatchFields.ts
  src/types.ts
  src/useFieldArray.ts
  src/useForm.test.tsx
  src/useForm.ts
Labels: bug, enhancement

#1295 💪 improve testing for watch field array
  .gitignore
  app/src/app.tsx
  app/src/watchUseFieldArray.tsx
  cypress/integration/watchUseFieldArray.ts
  src/useFieldArray.test.ts
Labels: status: working in progress

#1296 allow Controller to be focus while there is an error
  src/controller.tsx
  src/logic/focusErrorField.ts
  src/types.ts
Labels: enhancement
