Repository react-hook-form/react-hook-form, pull requests merged in 2020-04, with the labels that each got.

#1339 💪 improve watch() with useFieldArray
  app/src/app.tsx
  cypress/integration/watchUseFieldArray.ts
  src/useFieldArray.ts
  src/useForm.ts
Labels: enhancement, status: working in progress

#1338 fix #1333 web issue around reset with radio and checkbox only
  src/useForm.test.tsx
  src/useForm.ts
  src/utils/isRadioOrCheckbox.ts
Labels: bug

#1329 Lint test files and ignore `@ts-ignore` rule within them.
  .eslintrc.js
  package.json
  src/utils/onDomRemove.test.ts
Labels: enhancement

#1397 watch internal TS improvement
  src/contextTypes.ts
  src/types.ts
  src/useForm.ts
Labels: enhancement

#1407 Enable Proxy check React Native
  src/useForm.ts
Labels: enhancement

#1405 fix #1404 reset default values with useFieldArray
  cypress/integration/useFieldArray.ts
  src/useFieldArray.ts
  src/useForm.ts
Labels: status: working in progress

#1409 fix #1408 useFieldArray with Controller value gets reset
  src/controller.tsx
  src/useForm.ts
Labels: bug

#1328 Feature: support getValues by field name
  README.md
  src/contextTypes.ts
  src/logic/getFieldValue.test.ts
  src/types.ts
  src/useForm.ts
  yarn.lock
Labels: feature, waiting-up-vote

#1412 improve setValue type
  app/src/setValue.tsx
  src/contextTypes.ts
  src/types.ts
  src/useForm.ts
Labels: enhancement, status: working in progress

#1393 Enhancement: useForm code clean up.
  examples/FieldArray.tsx
  package.json
  src/logic/focusOnErrorField.test.ts
  src/logic/focusOnErrorField.ts
  src/logic/shouldRenderBasedOnError.test.ts
  src/logic/shouldRenderBasedOnError.ts
  src/useForm.test.tsx
  src/useForm.ts
  src/utils/isFileListObject.ts
Labels: enhancement

#1448 RHF's enhancement
  cypress/integration/basic.ts
  cypress/integration/basicSchemaValidation.ts
  cypress/integration/controller.ts
  cypress/integration/customSchemaValidation.ts
  cypress/integration/manualRegisterForm.ts
  src/logic/getRadioValue.ts
  src/utils/compareObject.test.ts
  src/utils/compareObject.ts
  src/utils/fillEmptyArray.test.ts
  src/utils/insert.test.ts
  src/utils/isNullOrUndefined.ts
  src/utils/isRadioOrCheckbox.test.ts
  src/utils/isRegex.test.ts
  src/utils/isUndefined.test.ts
Labels: enhancement

#1444 fix #1441 umd build process variable
  package.json
  rollup.min.config.js
  rollup/rollup.config.js
  rollup/rollup.ie11.config.js
  rollup/rollup.min.config.js
  rollup/rollup.umd.config.js
  yarn.lock
Labels: enhancement

#1492 V6 useForm: Feature/react-hook-form-resolvers
  app/package.json
  app/src/basicSchemaValidation.tsx
  app/src/formStateWithSchema.tsx
  app/src/isValid.tsx
  app/src/setValueWithSchema.tsx
  app/yarn.lock
  cypress/integration/basicSchemaValidation.ts
  cypress/integration/customSchemaValidation.ts
  cypress/integration/formStateWithSchema.ts
  cypress/integration/isValid.ts
  cypress/integration/setValueWithSchema.ts
  package.json
  src/useForm.ts
Labels: status: working in progress

#1503 support NestedValue type
  app/src/defaultValues.tsx
  app/src/setValue.tsx
  cypress/integration/defaultValues.ts
  cypress/integration/setValue.ts
  src/contextTypes.ts
  src/logic/assignWatchFields.ts
  src/types.ts
  src/useFieldArray.ts
  src/useForm.test.tsx
  src/useForm.ts
Labels: TS, feature request

#1542 improve generics type naming
  .eslintrc.js
  src/contextTypes.ts
  src/controller.tsx
  src/errorMessage.tsx
  src/logic/mapIds.ts
  src/types.ts
  src/useFieldArray.ts
  src/useForm.ts
  src/useFormContext.tsx
Labels: TS, status: working in progress
